// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lipqduurjuahriznyaqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcHFkdXVyanVhaHJpem55YXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTY1NjUsImV4cCI6MjA1OTY5MjU2NX0.Bu-WebtQgxU56XrwzE2rDaohx7MxUEEbUgekVpbuzsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);